[task][buildah] - v0.5: option to provide container registry credentials in a workspace
tektoncd/catalog pull request #1027
Opened 2022-07-26 10:54 UTC by zroubalik

Signed-off-by: Zbynek Roubalik <zroubalik@gmail.com>

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Follows the [authoring recommendations](https://github.com/tektoncd/catalog/blob/main/recommendations.md)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [x] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [x] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [x] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [x] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [x] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

2022-07-26 13:42 UTC, vinamra28 commented
/ok-to-test

2022-07-28 02:23 UTC, vinamra28 requested changes

2022-07-28 02:23 UTC, vinamra28 commented on task/buildah/0.5/README.md
> +kubectl apply -f https://raw.githubusercontent.com/tektoncd/catalog/main/task/buildah/0.4/buildah.yaml
```suggestion
kubectl apply -f https://raw.githubusercontent.com/tektoncd/catalog/main/task/buildah/0.5/buildah.yaml
```

2022-07-28 07:39 UTC, zroubalik commented on task/buildah/0.5/README.md
> +kubectl apply -f https://raw.githubusercontent.com/tektoncd/catalog/main/task/buildah/0.4/buildah.yaml
Good catch, fixed, thanks.

2022-07-28 15:50 UTC, zroubalik commented
/retest

2022-07-31 09:04 UTC, vinamra28 commented
/test .*

2022-07-31 09:07 UTC, vinamra28 commented
> Catlin Output
> ```
> FILE: task/buildah/0.5/buildah.yaml
> HINT : Task: tekton.dev/v1beta1 - name: "buildah" is missing a readable display name annotation("tekton.dev/displayName")
> WARN : Step "build" uses image "$(params.BUILDER_IMAGE)" that contains variables; skipping validation
> ```
> 
> Catlin script lint Output
> ```
> ERROR: /usr/bin/shellcheck, [-s sh] failed:
> 
> In buildah-build line 2:
> [[ "$(workspaces.sslcertdir.bound)" == "true" ]] && CERT_DIR_FLAG="--cert-dir $(workspaces.sslcertdir.path)"
> ^-- SC3010: In POSIX sh, [[ ]] is undefined.
> 
> 
> In buildah-build line 3:
> buildah ${CERT_DIR_FLAG} --storage-driver=$(params.STORAGE_DRIVER) bud \
>         ^--------------^ SC2086: Double quote to prevent globbing and word splitting.
>                                           ^----------------------^ SC2046: Quote this to prevent word splitting.
> 
> Did you mean: 
> buildah "${CERT_DIR_FLAG}" --storage-driver=$(params.STORAGE_DRIVER) bud \
> 
> 
> In buildah-build line 4:
>   $(params.BUILD_EXTRA_ARGS) --format=$(params.FORMAT) \
>   ^------------------------^ SC2046: Quote this to prevent word splitting.
>                                       ^--------------^ SC2046: Quote this to prevent word splitting.
> 
> 
> In buildah-build line 5:
>   --tls-verify=$(params.TLSVERIFY) --no-cache \
>                ^-----------------^ SC2046: Quote this to prevent word splitting.
> 
> 
> In buildah-build line 6:
>   -f $(params.DOCKERFILE) -t $(params.IMAGE) $(params.CONTEXT)
>      ^------------------^ SC2046: Quote this to prevent word splitting.
>                              ^-------------^ SC2046: Quote this to prevent word splitting.
>                                              ^---------------^ SC2046: Quote this to prevent word splitting.
> 
> 
> In buildah-build line 7:
> [[ "$(params.SKIP_PUSH)" == "true" ]] && echo "Push skipped" && exit 0
> ^-- SC3010: In POSIX sh, [[ ]] is undefined.
> 
> 
> In buildah-build line 8:
> [[ "$(workspaces.dockerconfig.bound)" == "true" ]] && export DOCKER_CONFIG="$(workspaces.dockerconfig.path)"
> ^-- SC3010: In POSIX sh, [[ ]] is undefined.
>                                                              ^-----------^ SC2155: Declare and assign separately to avoid masking return values.
> 
> 
> In buildah-build line 9:
> buildah ${CERT_DIR_FLAG} --storage-driver=$(params.STORAGE_DRIVER) push \
>         ^--------------^ SC2086: Double quote to prevent globbing and word splitting.
>                                           ^----------------------^ SC2046: Quote this to prevent word splitting.
> 
> Did you mean: 
> buildah "${CERT_DIR_FLAG}" --storage-driver=$(params.STORAGE_DRIVER) push \
> 
> 
> In buildah-build line 10:
>   $(params.PUSH_EXTRA_ARGS) --tls-verify=$(params.TLSVERIFY) \
>   ^-----------------------^ SC2046: Quote this to prevent word splitting.
>                                          ^-----------------^ SC2046: Quote this to prevent word splitting.
> 
> 
> In buildah-build line 11:
>   --digestfile /tmp/image-digest $(params.IMAGE) \
>                                  ^-------------^ SC2046: Quote this to prevent word splitting.
> 
> 
> In buildah-build line 12:
>   docker://$(params.IMAGE)
>            ^-------------^ SC2046: Quote this to prevent word splitting.
> 
> 
> In buildah-build line 13:
> cat /tmp/image-digest | tee $(results.IMAGE_DIGEST.path)
>     ^---------------^ SC2002: Useless cat. Consider 'cmd < file | ..' or 'cmd file | ..' instead.
>                             ^--------------------------^ SC2046: Quote this to prevent word splitting.
> 
> 
> In buildah-build line 14:
> echo "$(params.IMAGE)" | tee $(results.IMAGE_URL.path)
>      ^---------------^ SC2005: Useless echo? Instead of 'echo $(cmd)', just use 'cmd'.
>                              ^-----------------------^ SC2046: Quote this to prevent word splitting.
> 
> For more information:
>   https://www.shellcheck.net/wiki/SC2046 -- Quote this to prevent word splitt...
>   https://www.shellcheck.net/wiki/SC2155 -- Declare and assign separately to ...
>   https://www.shellcheck.net/wiki/SC3010 -- In POSIX sh, [[ ]] is undefined.
> ```

@zroubalik can you please resolve these errors? 😅

2022-08-01 14:23 UTC, zroubalik commented
@vinamra28 I am not sure, those errors are completely unrelated to the changes I submitted?

2022-08-03 01:45 UTC, vinamra28 commented
nevermind @zroubalik, CI is fixed now.
/lgtm
Thanks for your contribution 😄

2022-08-03 15:05 UTC, zroubalik commented
So, can we merge this one? :)

2022-08-03 18:21 UTC, piyush-garg commented
/lgtm

2022-08-03 23:12 UTC, vinamra28 approved these changes

2022-08-09 06:19 UTC, piyush-garg commented
/retest

2022-08-09 07:34 UTC, merged