Fixed typo
tektoncd/catalog pull request #509
Opened 2020-09-16 12:30 UTC by tmshn

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [ ] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [ ] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [ ] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [ ] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [ ] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

2020-09-16 12:53 UTC, vinamra28 requested changes
Thank you for the PR :+1: 
/ok-to-test

2020-09-16 12:53 UTC, vinamra28 commented on task/git-cli/0.1/README.md
> +in the `password` field while adding secrets.
This line should not change. Could you please look at it.

2020-09-16 13:14 UTC, Divyansh42 approved these changes
/lgtm

2020-09-16 13:15 UTC, vinamra28 approved these changes
/lgtm

2020-09-16 13:35 UTC, piyush-garg approved these changes
/lgtm

2020-09-17 10:50 UTC, vdemeester approved these changes
/meow

2020-09-17 10:52 UTC, merged