add sparse clone
tektoncd/catalog pull request #638
Opened 2021-01-30 22:06 UTC by a-rothwell

# Changes

I have added sparse-checkout capabilities to the git-clone task. I have also created a sample based on the others.

 I tested this using the nightly image: 
https://console.cloud.google.com/gcr/images/tekton-nightly/GLOBAL/github.com/tektoncd/pipeline/cmd/git-init@sha256:54f18d7519e4249da6fc6c17af8e7cd9d72d0ba54d47e0bd584f58cfc9617142/details?tab=info

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [x] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [x] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [x] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [x] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [x] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

2021-01-31 07:05 UTC, vinamra28 commented
hi @a-rothwell, I see that there is a new param being added and because of this some users of this task might face some issue. Can you please bump the new version of the task and avoid changing the current task version `0.2`?

2021-01-31 19:14 UTC, a-rothwell commented
Hi, I have bumped the task version and made my changes!

Thanks!

2021-02-01 08:22 UTC, chmouel commented
/ok-to-test

Thanks @a-rothwel

Here is a diff between the directory to make it easier to review for others : 

https://psty.io/p?q=f5c7f

/lgtm

2021-02-01 08:56 UTC, vinamra28 requested changes

2021-02-01 08:56 UTC, vinamra28 commented on task/git-clone/0.3/git-clone.yaml
> +    tekton.dev/pipelines.minVersion: "0.12.1"
can you please change the `pipelines.minVersion` to `0.21.0`?

2021-02-01 08:56 UTC, chmouel commented
Maybe we should wait the `git-init` related change gets into an official image release of pipeline

/hold

2021-02-17 11:45 UTC, vinamra28 commented
/retest

2021-02-17 12:29 UTC, vinamra28 commented
/retest

2021-02-17 13:08 UTC, vinamra28 reviewed
a couple of comments otherwise looks good

2021-02-17 13:08 UTC, vinamra28 commented on task/git-clone/0.3/git-clone.yaml
> +    subdirectory param.
can we add somewhere in the description that `0.3` version now supports `sparse checkout` as well?

2021-02-17 13:08 UTC, vinamra28 commented on task/git-clone/0.3/README.md
> +as well as
same here in the README can we somewhere add that git-clone task can now supports sparse checkout ?

2021-02-24 18:00 UTC, vinamra28 commented
/test .*

2021-02-24 18:01 UTC, vinamra28 commented
/kind feature

2021-02-24 21:04 UTC, a-rothwell commented
/test

2021-02-25 02:15 UTC, vinamra28 commented
/retest

2021-02-25 04:30 UTC, vinamra28 reviewed
/lgtm

2021-02-25 06:56 UTC, vinamra28 commented
/hold cancel

2021-02-26 14:39 UTC, sbwsg approved these changes

2021-02-26 14:40 UTC, merged