aws-cli: Make `secrets` workspace optional
tektoncd/catalog pull request #641
Opened 2021-02-02 11:04 UTC by andsens

Credentials can be passed to the aws-cli via instance roles (with e.g. `kiam`).
So an installation of this task could look like this:

```
kind: Kustomization
resources:
- https://raw.githubusercontent.com/tektoncd/catalog/master/task/aws-cli/0.1/aws-cli.yaml
patchesStrategicMerge:
- |-
	apiVersion: tekton.dev/v1beta1
	kind: Task
	metadata:
	  name: aws-cli
	  annotations:
	    iam.amazonaws.com/role: tekton-upload
```

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [ ] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [ ] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [ ] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [ ] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [ ] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

2021-02-02 14:37 UTC, chmouel commented
/ok-to-test
/lgtm

2021-02-02 14:45 UTC, vinamra28 commented
hi @andsens, can you please bump the task version as current `pipeline.minVersion` is `0.12.1` which doesn't support `optional` workspaces. Optional workspaces support came in Pipelines version `0.17.0`

2021-02-02 14:48 UTC, chmouel commented
Maybe bump the task number to from 0.1 to 0.2

2021-02-03 08:40 UTC, andsens commented
@vinamra28 @chmouel done, good catch.

2021-02-03 09:21 UTC, chmouel commented
@andsens you may have to do the CLA validation so we can go forward on this, thanks

2021-02-03 09:35 UTC, Divyansh42 requested changes

2021-02-03 09:35 UTC, Divyansh42 commented on task/aws-cli/0.2/aws-cli.yaml
> +    - name: source
As we are bumping the `minPipelineVersion` for this task, could you please also make the `source` workspace optional as well?

2021-02-03 09:35 UTC, Divyansh42 commented on task/aws-cli/0.2/README.md
> +See [here](../0.1/samples/run.yaml) for example of `aws s3` command.
```suggestion
See [here](../0.2/samples/run.yaml) for example of `aws s3` command.
```

2021-02-03 09:35 UTC, Divyansh42 commented on task/aws-cli/0.2/README.md
> +This [samples](../0.1/samples/secret.yaml), can be referred to create secret file for aws credentials.
```suggestion
This [samples](../0.2/samples/secret.yaml), can be referred to create secret file for aws credentials.
```

2021-02-03 09:35 UTC, Divyansh42 commented on task/aws-cli/0.2/README.md
> +In the [samples](../0.1/samples/run.yaml), ConfigMap as the volume is used. In place of ConfigMap, any volume supported in workspace can be used.
```suggestion
In the [samples](../0.2/samples/run.yaml), ConfigMap as the volume is used. In place of ConfigMap, any volume supported in workspace can be used.
```

2021-02-03 09:35 UTC, Divyansh42 commented on task/aws-cli/0.2/README.md
> +[This](../0.1/samples/secret.yaml) example can be referred to create `aws-credentials`.
```suggestion
[This](../0.2/samples/secret.yaml) example can be referred to create `aws-credentials`.
```

2021-02-03 09:35 UTC, Divyansh42 commented on task/aws-cli/0.2/README.md
> +    ```
You can also remove this block once we change the workspaces to `optional`.

2021-02-04 09:39 UTC, andsens commented on task/aws-cli/0.2/README.md
> +    This workspace can be omitted when using instance-profile credentials.
I mean... it's pretty clear. When you use instance-profile credentials, you don't need to mount them. They'll be provided through 169.254.169.254.

2021-02-04 09:47 UTC, andsens commented
@chmouel that "Easy"CLA is everything but. I already signed it yesterday on behalf of the company and have received the confirmation email. Now when I try repeating that I get webpack `require` errors when selecting my company.

2021-02-04 10:35 UTC, chmouel commented
@andsens  I am not sure how to rekick the validation, maybe @vdemeester can help?

2021-02-04 15:37 UTC, vinamra28 commented
/check-cla

2021-02-04 16:30 UTC, andsens commented
@chmouel @vinamra28 seems we'll have to wait a little :-/
https://jira.linuxfoundation.org/plugins/servlet/theme/portal/4/SUPPORT-3969

2021-02-05 07:41 UTC, andsens commented
/check-cla

2021-02-05 14:08 UTC, andsens commented
OK wth. I've definitely approved everything. I don't have a clue why the CLA isn't approved yet.

2021-02-08 08:58 UTC, andsens commented
there we go!

2021-02-08 09:38 UTC, vinamra28 reviewed
/lgtm

2021-02-08 09:52 UTC, Divyansh42 reviewed
/lgtm

Thanks :+1:

2021-02-08 10:01 UTC, chmouel commented
/lgtm
/approve

thank you,

2021-02-08 10:11 UTC, merged