Moves a pipeline `gke-deploy-build-push` from task dir to pipeline dir
tektoncd/catalog pull request #667
Opened 2021-03-08 14:07 UTC by PuneetPunamiya

This patch includes-

   Currently we have a file called `build-push-gke-deploy`
   which has multiple resources in one file, this patch moves
   the pipeline to the pipeline  directory and it's corresponding
   task to the support directory

Signed-off-by: Puneet Punamiya <ppunamiy@redhat.com>

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [ ] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [ ] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [ ] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [ ] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [ ] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

2021-03-08 15:31 UTC, vinamra28 requested changes

2021-03-08 15:31 UTC, vinamra28 commented on pipeline/gke-deploy-build-push/0.1/gke-deploy-build-push.yaml
> +        name: deploy
I guess this should be `gke-deploy` as we are referring to the existing catalog task.

2021-03-08 15:31 UTC, vinamra28 commented on pipeline/gke-deploy-build-push/0.1/gke-deploy-build-push.yaml
> +    - name: source
can we add a bit description about workspace as well so that folks using CLI could get to know why and for what purpose this workspace used?

2021-03-09 10:43 UTC, vinamra28 reviewed
/lgtm

2021-03-12 12:46 UTC, sbwsg commented
/approve

2021-03-12 12:46 UTC, sbwsg commented
/approve cancel

2021-03-12 12:46 UTC, sbwsg commented
Sorry just realized there's still a file in the task directory.  I checked out the branch and I still see a file on its own at the following path:

`task/build-push-gke-deploy/0.1/build-push-gke-deploy.yaml`

2021-03-15 12:06 UTC, vinamra28 commented
/test .*

2021-03-15 12:39 UTC, sbwsg commented
I see the name changed from `build-push-gke-deploy` to `gke-deploy-build-push`.  Can we leave the name the same for the time being?  I think it's called `build-push-gke-deploy` because that's the order the Pipeline runs in.  It loses that meaning if we change the name and `gke-deploy-build-push` reads a bit nonsensical.

2021-03-16 13:11 UTC, sbwsg approved these changes
Thanks @PuneetPunamiya !

2021-03-16 15:02 UTC, vinamra28 commented
/lgtm

2021-03-16 15:03 UTC, merged