Parameterizing orka task images
tektoncd/catalog pull request #939
Opened 2022-03-07 16:05 UTC by hokadiri

# Changes

**What:**
Parameterizing orka task images so it can be overriden

**Why:**
docker.io not accessible from internal networks. one needs to either access it via a proxy OR copy the image into an internal docker registry. Doing this requires modifying the `image` var.  

**How:**
Creating params var for task image which defaults to orka docker.io image.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Follows the [authoring recommendations](https://github.com/tektoncd/catalog/blob/main/recommendations.md)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality of task changed or new task added)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Complies with [Catalog Organization TEP][TEP], see [example]. **Note** [An issue has been filed to automate this validation][validation]
  - [x] File path follows  `<kind>/<name>/<version>/name.yaml`
  - [x] Has `README.md` at `<kind>/<name>/<version>/README.md`
  - [x] Has mandatory `metadata.labels` - `app.kubernetes.io/version` the same as the `<version>` of the resource
  - [x] Has mandatory `metadata.annotations` `tekton.dev/pipelines.minVersion`
  - [x] mandatory `spec.description` follows the convention

          ```

          spec:
            description: >-
              one line summary of the resource

              Paragraph(s) to describe the resource.
          ```

_See [the contribution guide](https://github.com/tektoncd/catalog/blob/master/CONTRIBUTING.md)
for more details._

---

[TEP]: https://github.com/tektoncd/community/blob/master/teps/0003-tekton-catalog-organization.md
[example]: https://github.com/tektoncd/catalog/tree/master/task/git-clone/0.1
[validation]:  https://github.com/tektoncd/catalog/issues/413

2022-03-07 16:54 UTC, afrittoli commented
/ok-to-test

2022-03-08 10:10 UTC, afrittoli commented
@chmouel @vdemeester would this change warrant a new version of the task?
The CLA is being fixed by as a CCLA by @hokadiri's company.

2022-03-11 18:41 UTC, chmouel commented
this doesn't break anything, so I don't think it's needed....

2022-03-17 21:08 UTC, afrittoli commented
@tektoncd/catalog-maintainers cla fixed now, ready for review 🙇

2022-03-17 21:25 UTC, chmouel commented
/lgtm

2022-03-18 04:38 UTC, piyush-garg requested changes

2022-03-18 04:38 UTC, piyush-garg commented on task/orka-deploy/0.1/README.md
> +| `task-image` | The docker image used to run the task steps. | --- |
`---` should be replaced by default value

2022-03-18 04:38 UTC, piyush-garg commented on task/orka-full/0.1/README.md
> +| `task-image` | The docker image used to run the task steps. | --- |
`---` should be replaced by default value

2022-03-18 04:38 UTC, piyush-garg commented on task/orka-init/0.1/README.md
> +| `task-image` | The docker image used to run the task steps. | --- |
`---` should be replaced by default value

2022-03-18 04:38 UTC, piyush-garg commented on task/orka-teardown/0.1/README.md
> +| `task-image` | The docker image used to run the task steps. | --- |
`---` should be replaced by default value

2022-03-18 04:38 UTC, piyush-garg commented on task/orka-deploy/0.1/README.md
> +| `task-image` | The docker image used to run the task steps. | --- |
I think we should have the parameter like `orka-image` instead of `task-image`

2022-03-18 04:39 UTC, piyush-garg commented
Please squash the commits also

2022-03-21 04:40 UTC, piyush-garg commented
/diff

2022-03-21 04:42 UTC, piyush-garg commented
@hokadiri Please squash the commits into one

2022-03-21 05:51 UTC, hokadiri commented
@piyush-garg ,done

2022-03-21 05:54 UTC, vinamra28 commented
@hokadiri, I guess the commits are still not squashed 😅, still 10 commits 😅

2022-03-21 06:14 UTC, hokadiri commented
hmm, 
@vinamra28 
Maybe i'm not familiar squashing commits on github's.
I squashed via the did interactive rebase `git rebase -i HEAD~[X]`. and got this commit https://github.com/tektoncd/catalog/pull/939/commits/bce59dbd16d6ecf58d7347d01dab5f27f36b69fb.

is there a different way of squashing?

2022-03-21 06:47 UTC, vinamra28 commented
closing in favour of #952

2022-03-21 06:47 UTC, closed without merging